#!/usr/bin/php
<?
/*
phpGSB - PHP Google Safe Browsing Implementation
Version 0.1 (ALPHA) - Not recommended for production use
Released under New BSD License (see LICENSE)
Copyright (c) 2010, Sam Cleaver (Beaver6813, Beaver6813.com)
All rights reserved.

UPDATER EXAMPLE
*/

require_once('config.php');
require_once( dirname(__FILE__).'/../../../includes/load-yourls.php' );

$phpgsb = new phpGSB(YOURLS_DB_NAME, YOURLS_DB_USER, YOURLS_DB_PASS, YOURLS_DB_HOST, false);
//Obtain an API key from: http://code.google.com/apis/safebrowsing/key_signup.html
$phpgsb->apikey = GSB_APIKEY;
$phpgsb->usinglists = array('googpub-phish-shavar','goog-malware-shavar');
$phpgsb->runUpdate();
$phpgsb->close();
?>
